---
- hosts: nodes
  tasks:
  - name: Restart service gluster and enabled, in all cases
    service:
       name: glusterd
       state: restarted
       enabled: yes
  - name: Create bricks
    file:
       path: /brick1/one
       state: directory
       mode: 0775
    file:
       path: /brick2/one
       state: directory
       mode: 0775
    file:
       path: /brick3/one
       state: directory
       mode: 0775
#################### logical volume
#
  - name: Create a PV disk 
    lvg:
       pvs: /dev/sdc
       vg: vg1
#  - name: Create a logical pool
#    lvol:
#       vg: vg1
#       lv: pool
#       size: 100%FREE

  - name: create Thinpool
    lvol:
      vg: vg1
      thinpool: pool
      size: 8g
  
  - name: Create lvm 1
    lvol:
       vg: vg1
       lv: lv1
       thinpool: pool
       size: 1g
  
  - name: Create lvm 2
    lvol:
       vg: vg1
       lv: lv2
       thinpool: pool
       size: 1g
  - name: Create lvm 3
    lvol:
       vg: vg1
       lv: lv3
       thinpool: pool
       size: 1g
  - name: Create a xfs filesystem on lv1
    filesystem:
      fstype: xfs
      dev: /dev/vg1/lv1
  - name: Create a xfs filesystem on lv2
    filesystem:
      fstype: xfs
      dev: /dev/vg1/lv2
  - name: Create a xfs filesystem on lv3
    filesystem:
      fstype: xfs
      dev: /dev/vg1/lv3

########################## Mounting bricks


  - name: mount lv1 
    mount:
      path: /brick1
      src: /dev/vg1/lv1
      fstype: xfs
      state: mounted
      backup: no
      boot: yes
  
  - name: mount lv2
    mount:
      path: /brick2
      src: /dev/vg1/lv2
      fstype: xfs
      state: mounted
      backup: no
      boot: yes

  - name: mount lv3
    mount:
      path: /brick3
      src: /dev/vg1/lv3
      fstype: xfs
      state: mounted
      backup: no
      boot: yes

########################## Creating gluster Volume
- hosts: master
  tasks:


  - name: Create a trusted storage pool
    gluster_peer:
       state: present
       nodes: 192.168.122.20
       nodes: 192.168.122.30


  - name: Creating replicated volume
    gluster_volume:
      state: present
      name: Vol1
      bricks: /brick1/one
      replicas: 3
      cluster:
        - 192.168.122.10
        - 192.168.122.20
        - 192.168.122.30
    run_once: true


  - name: Creating distributed volume
    gluster_volume:
      state: present
      name: Vol2
      bricks: /brick2/one
      replicas: 0
      cluster:
        - 192.168.122.10
        - 192.168.122.20
        - 192.168.122.30
    run_once: true


  - name: Creating arbitary volume
    gluster_volume:
      state: present
      name: Vol3
      bricks: /brick3/one
      replicas: 3
      arbiters: 1
      cluster:
        - 192.168.122.10
        - 192.168.122.20
        - 192.168.122.30
    run_once: true


###########################################



  - name: start replicated gluster volume
    gluster_volume:
      state: started
      name: Vol1
  
  - name: start distributed gluster volume
    gluster_volume:
      state: started
      name: Vol2


  - name: start arbitary gluster volume
    gluster_volume:
      state: started
      name: Vol3
  


###################################################
  - name: Create dir inside mnt point for vol1
    file:
      path: /mnt/gluster_vol
      state: directory
      mode: 0775
  
  - name: Mounting Vol1
    mount:
      src: 192.168.122.10:/Vol1
      path: /mnt/gluster_vol
      fstype: glusterfs
      opts: _netdev
      state: mounted
      backup: no
      boot: yes




  - name: Create dir inside mnt point for vol2
    file:
      path: /mnt/gluster_vol2
      state: directory
      mode: 0775

  - name: Mounting Vol2
    mount:
      src: 192.168.122.10:/Vol2
      path: /mnt/gluster_vol2
      fstype: glusterfs
      opts: _netdev
      state: mounted
      backup: no
      boot: yes



  - name: Create dir inside mnt point vol3
    file:
      path: /mnt/gluster_vol3
      state: directory
      mode: 0775

  - name: Mounting Vol3
    mount:
      src: 192.168.122.10:/Vol3
      path: /mnt/gluster_vol3
      fstype: glusterfs
      opts: _netdev
      state: mounted
      backup: no
      boot: yes



